Adding qualifying_results()
alec-kr/F1PyStats pull request #50
Opened 2022-10-04 23:37 UTC by achiverram28

## Description

I have created a python file  called qualifying_result.py which contains the QualifyResult class with get_positions(), get_names(),get_driver_numbers(),get_constructors(),get_qualifying_times() methods to get the driver position , driver name , driver number , constructor name , the three qualifying times.

I have created the first_3_qualifying_results_2022.json for sample data for testing

I have created test_ qualifying_result.py file to test the correctness of  qualifying_result.py file.

## Related Issue(s)

Fixes #43  

## User-facing Changes

## Screenshots (If necessary)

2022-10-04 23:59 UTC, achiverram28 commented
Can u please check it

2022-10-05 00:48 UTC, alec-kr reviewed
Great work!

2022-10-05 00:49 UTC, alec-kr requested changes
Pylint is not happy :(
![image](https://user-images.githubusercontent.com/52685467/193956031-c925cbd9-9518-41de-8482-839b5708e7a6.png)

You should remove all the trailing whitespaces as outlined, and also add a class docstring to the new class you created.

2022-10-05 00:52 UTC, alec-kr requested changes

2022-10-05 00:52 UTC, alec-kr commented on tests/test_qualifying_results.py
> +        assert three_times == [('1:18.881', '1:18.606', '1:17.868'), ('1:18.580', '1:18.611', '1:18.154'), ('1:18.834', '1:18.340', '1:18.240')]
This line is too long. Consider adding each new set of times to a new line.

2022-10-05 17:48 UTC, achiverram28 commented
please check it now

2022-10-05 21:04 UTC, alec-kr requested changes
You have to update the table in the README to include the new function. Be sure to include the function call, a short description, and the returned data type.

Your code is also broken :(
![Screenshot from 2022-10-05 17-09-39](https://user-images.githubusercontent.com/52685467/194164356-a9b62792-ae5f-4ed6-a85e-cac0164fdac2.png)

Based on the error returned above, it appears as though you are trying to get the Q3 time for drivers that didn't actually make it into Q3.

2022-10-05 23:43 UTC, achiverram28 commented
![F33AEE10-6ED5-471D-84DC-FF2973F35ACE_1_105_c](https://user-images.githubusercontent.com/97288756/194183255-bc705656-b4a5-418f-82d5-7a048a1b5cfc.jpeg)
See its working properly

2022-10-05 23:47 UTC, alec-kr commented
You are only testing the first 3 entries. The first 3 drivers have obviously made it into all 3 qualifying sessions, therefore your test will pass.

You have clearly not run the ```fp.qualifying_results()``` to test your code. Please do so, and correct the error

2022-10-05 23:49 UTC, achiverram28 commented
<img width="906" alt="0ACDDD5E-3B38-4A1B-A05F-3A37D49F2717" src="https://user-images.githubusercontent.com/97288756/194183772-042372b7-d754-4d54-9a8a-889a01fba6eb.png">
See here the details of q2 ,q3 is missing in the api

2022-10-06 02:09 UTC, alec-kr commented
## Reproducing your error
To reproduce your code error on your system, you can:
- Install your fork of the repo
- Import the package as ```fp``` or anything you like
- Run ```fp.qualifying_results()```

## The Problem
The test you are showing me in the screenshot is only testing the top 3 drivers. The top 3 drivers obviously made it into all qualifying sessions, as seen in your data. However, if you were to test the 3 slowest drivers, you would notice that your test will fail.

Your current code is checking for the keys ```Q1```, ```Q2```, ```Q3```, regardless if these keys exist or not. 

## The Solution
What you should do, is implement a test to check if the key exists, before attempting to get the qualifying times. Have a look at [this code snippet](https://github.com/alec-kr/F1PyStats/blob/main/f1pystats/driver_info.py#L24-L28) from [driver_info.py](https://github.com/alec-kr/F1PyStats/blob/main/f1pystats/driver_info.py). Here, I am checking the JSON data to determine if the ```permanentNumber``` key is in the current data. If the key exists, I append the value stored at that key. However, if the key does not exist, ```None``` is appended to the list.

You can copy and implement this code into your ```qualifying_results.py``` file, in the ```get_qualifying_times()``` function. This function should contain a for loop, looping over ```self.results```, and checking if the keys for each qualifying session exist. If a particular key exists, only then should you get the value stored at that key, and add it to a list, as seen in [```driver_info.py```](https://github.com/alec-kr/F1PyStats/blob/main/f1pystats/driver_info.py#L24-L28)

2022-10-06 09:03 UTC, achiverram28 commented
Yeah I am implementing , this is was what even I THOUGHT after I saw the error

2022-10-06 09:12 UTC, achiverram28 commented
Bro can You check it now

2022-10-06 13:36 UTC, alec-kr commented
Your new code seems good. I will test the function later in the day.

2022-10-06 14:30 UTC, alec-kr requested changes
I have just tested the function @achiverram28. 

I'm not sure why you are returning a tuple inside the DataFrame. 

![Screenshot from 2022-10-06 10-27-30](https://user-images.githubusercontent.com/52685467/194339559-8c4a346c-8d18-4523-ba4e-5fb5eacbb949.png)

As seen in the photo above, you are just returning a tuple containing qualifying times for all 3 sessions. This is not quite neat, since it will be difficult for users to access this data from the function.

There should be separate headings for each set of qualifying times. You have a single column name stored as ```Q1,Q2,Q3```, when there should be three columns as shown here:

![Screenshot from 2022-10-06 10-28-52](https://user-images.githubusercontent.com/52685467/194340032-dd2e8ae5-a715-43c1-a12c-428b13a4207f.png)

2022-10-06 14:34 UTC, alec-kr commented
Maybe you can create separate methods in ```QualifyingResults``` to get the times from each session.

Example: ```get_q1_times()```, ```get_q2_times()```, ```get_q3_times()```

In your ```f1pystats.py```, you will create 3 separate variables for qualifying times, which will store the data for the 3 columns containing qualifying times.

2022-10-06 14:45 UTC, alec-kr commented
Note: Please ensure you install and test your package with the changes before submitting an updated PR

2022-10-07 11:19 UTC, achiverram28 commented
<img width="650" alt="Screenshot 2022-10-07 at 4 47 28 PM" src="https://user-images.githubusercontent.com/97288756/194541155-77ead9db-5a02-41dc-9453-3eb928b72a61.png">
Hope this is fine
And I have tested , I did not get any further errors
I am making a PR now

2022-10-07 12:52 UTC, alec-kr commented
I will test it locally later.

2022-10-07 23:44 UTC, alec-kr approved these changes
Tested and works well.
Feature functions as expected, so I will be merging it shortly.

Thank you for contributing 😁

2022-10-07 23:44 UTC, merged